let marido = 'João';
let esposa = 'Maria';
let filho = 'Eduardo';
let nascimento = 1984;
let casamento = 2012;
let bebe = 2015;
console.log(marido, 'nasceu em',nascimento,'.');
console.log('Em 2000', marido, 'conheceu', esposa,'.');
console.log(marido,'casou-se com', esposa,'em',casamento, '.');
console.log(esposa,'teve 1 filho com', marido, 'em',bebe,'.');
console.log('O Filho de', marido, 'chama-se', filho,'.');
marido= 'Henrique';
filho='Júlio';
esposa='Fernanda';
nascimento=1990;
casamento=2020;
bebe=2022;
console.log(marido, 'nasceu em',nascimento,'.');
console.log('Em 2000', marido, 'conheceu', esposa,'.');
console.log(marido,'casou-se com', esposa,'em',casamento, '.');
console.log(esposa,'teve 1 filho com', marido, 'em',bebe,'.');
console.log('O Filho de', marido, 'chama-se', filho,'.');